import Foundation
import XCTest
import Crypto
import Citadel

/// Parsing `ecdsa-sha2-nistp256/384/521` private keys out of the
/// `openssh-key-v1` container.
///
/// Every key these tests read is generated by `ssh-keygen` while the test runs,
/// into a temporary directory that is removed again in `tearDown`. No key
/// material is checked in, and none of it outlives the process.
///
/// The load-bearing assertion is `publicPointMatchesContainer`: the public key
/// derived from the parsed scalar `d` must equal the point `Q` the container
/// carries. `Q` is read straight out of the file by `OpenSSHContainerHeader`
/// below, which does not go through Citadel — so the two sides of that equality
/// come from independent readers, and the parser cannot satisfy it by agreeing
/// with itself.
final class ECDSAKeyTests: XCTestCase {
    /// How many freshly generated keys each round-trip test reads.
    ///
    /// More than one, because the interesting case is a private scalar whose
    /// leading byte is zero: `d` is written as an SSH mpint, so such a scalar
    /// is one byte shorter than the curve and has to be left-padded before it
    /// is a valid `rawRepresentation`. That happens for roughly 1 key in 256,
    /// so no fixed number of iterations makes it certain — but a loop is what
    /// gives the padding path any chance of being exercised at all, and the
    /// mpint's *other* shape, a leading 0x00 sign byte on a scalar whose top
    /// bit is set, shows up in about half of all keys.
    private static let iterations = 5

    private var workDirectory: URL!

    override func setUpWithError() throws {
        workDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("citadel-ecdsa-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: workDirectory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        if let workDirectory {
            try? FileManager.default.removeItem(at: workDirectory)
        }
        workDirectory = nil
    }

    // MARK: - Unencrypted round trips

    func testUnencryptedP256KeysReproduceTheContainerPoint() throws {
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 256)
            let privateKey = try P256.Signing.PrivateKey(sshEcdsa: key)
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 32,
                keyType: "ecdsa-sha2-nistp256",
                curve: "nistp256",
                container: key
            )
        }
    }

    func testUnencryptedP384KeysReproduceTheContainerPoint() throws {
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 384)
            let privateKey = try P384.Signing.PrivateKey(sshEcdsa: key)
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 48,
                keyType: "ecdsa-sha2-nistp384",
                curve: "nistp384",
                container: key
            )
        }
    }

    func testUnencryptedP521KeysReproduceTheContainerPoint() throws {
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 521)
            let privateKey = try P521.Signing.PrivateKey(sshEcdsa: key)
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 66,
                keyType: "ecdsa-sha2-nistp521",
                curve: "nistp521",
                container: key
            )
        }
    }

    // MARK: - Encrypted round trips

    func testEncryptedP256KeysReproduceTheContainerPoint() throws {
        let passphrase = "correct horse battery staple"
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 256, passphrase: passphrase)
            let privateKey = try P256.Signing.PrivateKey(
                sshEcdsa: key,
                decryptionKey: Data(passphrase.utf8)
            )
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 32,
                keyType: "ecdsa-sha2-nistp256",
                curve: "nistp256",
                container: key
            )
        }
    }

    func testEncryptedP384KeysReproduceTheContainerPoint() throws {
        let passphrase = "correct horse battery staple"
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 384, passphrase: passphrase)
            let privateKey = try P384.Signing.PrivateKey(
                sshEcdsa: key,
                decryptionKey: Data(passphrase.utf8)
            )
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 48,
                keyType: "ecdsa-sha2-nistp384",
                curve: "nistp384",
                container: key
            )
        }
    }

    func testEncryptedP521KeysReproduceTheContainerPoint() throws {
        let passphrase = "correct horse battery staple"
        for _ in 0..<Self.iterations {
            let key = try generateECDSAKey(bits: 521, passphrase: passphrase)
            let privateKey = try P521.Signing.PrivateKey(
                sshEcdsa: key,
                decryptionKey: Data(passphrase.utf8)
            )
            try assertMatchesContainer(
                privateKey.publicKey.x963Representation,
                scalar: privateKey.rawRepresentation,
                scalarSize: 66,
                keyType: "ecdsa-sha2-nistp521",
                curve: "nistp521",
                container: key
            )
        }
    }

    // MARK: - Failure modes, measured against the ed25519 arm

    /// An encrypted key opened without a passphrase must fail exactly the way
    /// the ed25519 arm fails, because that is the error macSCP already knows how
    /// to turn into "this key needs a passphrase".
    ///
    /// The comparison is against the error the ed25519 arm actually throws,
    /// captured in the same run — not against a spelling of it — because the
    /// type that carries it is internal to Citadel and cannot be named here.
    func testEncryptedKeyWithoutPassphraseFailsTheSameWayAsEd25519() throws {
        let passphrase = "correct horse battery staple"
        let ecdsaKey = try generateECDSAKey(bits: 256, passphrase: passphrase)
        let ed25519Key = try generateEd25519Key(passphrase: passphrase)

        let ecdsaError = try XCTUnwrap(errorThrown {
            _ = try P256.Signing.PrivateKey(sshEcdsa: ecdsaKey)
        })
        let ed25519Error = try XCTUnwrap(errorThrown {
            _ = try Curve25519.Signing.PrivateKey(sshEd25519: ed25519Key)
        })

        XCTAssertTrue(type(of: ecdsaError) == type(of: ed25519Error))
        XCTAssertEqual(String(reflecting: ecdsaError), String(reflecting: ed25519Error))

        // The positive check beside the negative one: the very same file parses
        // once the passphrase is supplied. Without this, the assertions above
        // would stay green if `sshEcdsa` started rejecting every encrypted key.
        XCTAssertNoThrow(
            try P256.Signing.PrivateKey(sshEcdsa: ecdsaKey, decryptionKey: Data(passphrase.utf8))
        )
    }

    /// A wrong passphrase must fail the way the ed25519 arm fails for a wrong
    /// passphrase — which is a different failure from "no passphrase at all",
    /// and this test also pins that the two are still different.
    func testWrongPassphraseFailsTheSameWayAsEd25519() throws {
        let passphrase = "correct horse battery staple"
        let wrongPassphrase = "not the passphrase"
        let ecdsaKey = try generateECDSAKey(bits: 256, passphrase: passphrase)
        let ed25519Key = try generateEd25519Key(passphrase: passphrase)

        let ecdsaError = try XCTUnwrap(errorThrown {
            _ = try P256.Signing.PrivateKey(
                sshEcdsa: ecdsaKey,
                decryptionKey: Data(wrongPassphrase.utf8)
            )
        })
        let ed25519Error = try XCTUnwrap(errorThrown {
            _ = try Curve25519.Signing.PrivateKey(
                sshEd25519: ed25519Key,
                decryptionKey: Data(wrongPassphrase.utf8)
            )
        })

        XCTAssertTrue(type(of: ecdsaError) == type(of: ed25519Error))
        XCTAssertEqual(String(reflecting: ecdsaError), String(reflecting: ed25519Error))

        let missingKeyError = try XCTUnwrap(errorThrown {
            _ = try P256.Signing.PrivateKey(sshEcdsa: ecdsaKey)
        })
        XCTAssertNotEqual(String(reflecting: ecdsaError), String(reflecting: missingKeyError))

        XCTAssertNoThrow(
            try P256.Signing.PrivateKey(sshEcdsa: ecdsaKey, decryptionKey: Data(passphrase.utf8))
        )
    }

    // MARK: - The two shapes of the mpint scalar

    /// A private scalar whose leading byte is zero is written as an mpint one
    /// byte shorter than the curve, and has to be left-padded before it is a
    /// `rawRepresentation`.
    ///
    /// The generated keys above reach that case about once in 256, which is too
    /// seldom to call a guard. So this test searches for such a scalar in
    /// process — where a key pair costs microseconds instead of a `ssh-keygen`
    /// fork — and builds the container around it with `OpenSSHContainerWriter`,
    /// which encodes `d` the way OpenSSH does and nothing else.
    func testScalarShorterThanTheCurveIsLeftPadded() throws {
        let key = try XCTUnwrap(
            findP256Key(matching: { $0.first == 0x00 }),
            "no P-256 scalar with a leading zero byte in \(Self.scalarSearchLimit) tries"
        )
        XCTAssertEqual(key.rawRepresentation.count, 32)

        let container = OpenSSHContainerWriter.p256Container(for: key)
        let parsed = try P256.Signing.PrivateKey(sshEcdsa: container)

        XCTAssertEqual(parsed.rawRepresentation, key.rawRepresentation)
        XCTAssertEqual(parsed.publicKey.x963Representation, key.publicKey.x963Representation)
    }

    /// The other shape: a scalar whose top bit is set carries a 0x00 sign byte,
    /// making the mpint one byte longer than the curve. Roughly half of all keys
    /// are like this, so the generated keys above cover it too — but only this
    /// test says so on purpose, and it sits beside the short case so neither can
    /// be broken without one of them going red.
    func testScalarWithTheTopBitSetKeepsItsSignByte() throws {
        let key = try XCTUnwrap(
            findP256Key(matching: { ($0.first ?? 0) & 0x80 != 0 }),
            "no P-256 scalar with the top bit set in \(Self.scalarSearchLimit) tries"
        )

        let container = OpenSSHContainerWriter.p256Container(for: key)
        let parsed = try P256.Signing.PrivateKey(sshEcdsa: container)

        XCTAssertEqual(parsed.rawRepresentation, key.rawRepresentation)
        XCTAssertEqual(parsed.publicKey.x963Representation, key.publicKey.x963Representation)
    }

    /// How many key pairs the searches above may draw. A leading zero byte
    /// appears in about 1 scalar in 256.
    private static let scalarSearchLimit = 20_000

    private func findP256Key(matching predicate: (Data) -> Bool) -> P256.Signing.PrivateKey? {
        for _ in 0..<Self.scalarSearchLimit {
            let key = P256.Signing.PrivateKey()

            if predicate(key.rawRepresentation) {
                return key
            }
        }

        return nil
    }

    // MARK: - Curve and type mismatches

    func testCurveMismatchNamesBothTypes() throws {
        let p256Key = try generateECDSAKey(bits: 256)
        let p384Key = try generateECDSAKey(bits: 384)
        let p521Key = try generateECDSAKey(bits: 521)

        XCTAssertThrowsError(try P256.Signing.PrivateKey(sshEcdsa: p384Key)) { error in
            XCTAssertEqual(
                error as? OpenSSHKeyTypeMismatch,
                OpenSSHKeyTypeMismatch(expected: "ecdsa-sha2-nistp256", found: "ecdsa-sha2-nistp384")
            )
        }
        XCTAssertThrowsError(try P384.Signing.PrivateKey(sshEcdsa: p521Key)) { error in
            XCTAssertEqual(
                error as? OpenSSHKeyTypeMismatch,
                OpenSSHKeyTypeMismatch(expected: "ecdsa-sha2-nistp384", found: "ecdsa-sha2-nistp521")
            )
        }
        XCTAssertThrowsError(try P521.Signing.PrivateKey(sshEcdsa: p256Key)) { error in
            XCTAssertEqual(
                error as? OpenSSHKeyTypeMismatch,
                OpenSSHKeyTypeMismatch(expected: "ecdsa-sha2-nistp521", found: "ecdsa-sha2-nistp256")
            )
        }

        // The positive check: each file parses under its own curve, so the three
        // assertions above are rejecting the curve and not the file.
        XCTAssertNoThrow(try P256.Signing.PrivateKey(sshEcdsa: p256Key))
        XCTAssertNoThrow(try P384.Signing.PrivateKey(sshEcdsa: p384Key))
        XCTAssertNoThrow(try P521.Signing.PrivateKey(sshEcdsa: p521Key))
    }

    func testNonECDSAKeyIsReportedAsAMismatchToo() throws {
        let ed25519Key = try generateEd25519Key()

        XCTAssertThrowsError(try P256.Signing.PrivateKey(sshEcdsa: ed25519Key)) { error in
            XCTAssertEqual(
                error as? OpenSSHKeyTypeMismatch,
                OpenSSHKeyTypeMismatch(expected: "ecdsa-sha2-nistp256", found: "ssh-ed25519")
            )
        }
        XCTAssertNoThrow(try Curve25519.Signing.PrivateKey(sshEd25519: ed25519Key))
    }

    // MARK: - The Data overloads

    func testDataOverloadsAgreeWithTheStringOverloads() throws {
        let p256Key = try generateECDSAKey(bits: 256)
        let p384Key = try generateECDSAKey(bits: 384)
        let p521Key = try generateECDSAKey(bits: 521)

        XCTAssertEqual(
            try P256.Signing.PrivateKey(sshEcdsa: Data(p256Key.utf8)).rawRepresentation,
            try P256.Signing.PrivateKey(sshEcdsa: p256Key).rawRepresentation
        )
        XCTAssertEqual(
            try P384.Signing.PrivateKey(sshEcdsa: Data(p384Key.utf8)).rawRepresentation,
            try P384.Signing.PrivateKey(sshEcdsa: p384Key).rawRepresentation
        )
        XCTAssertEqual(
            try P521.Signing.PrivateKey(sshEcdsa: Data(p521Key.utf8)).rawRepresentation,
            try P521.Signing.PrivateKey(sshEcdsa: p521Key).rawRepresentation
        )
    }

    // MARK: - Assertions

    private func assertMatchesContainer(
        _ derivedPoint: Data,
        scalar: Data,
        scalarSize: Int,
        keyType: String,
        curve: String,
        container: String,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let header = try OpenSSHContainerHeader(pemEncoded: container)
        XCTAssertEqual(header.keyType, keyType, file: file, line: line)
        XCTAssertEqual(header.curve, curve, file: file, line: line)
        XCTAssertEqual(header.point.count, 1 + 2 * scalarSize, file: file, line: line)
        XCTAssertEqual(scalar.count, scalarSize, file: file, line: line)
        XCTAssertEqual(derivedPoint, header.point, file: file, line: line)
    }

    private func errorThrown(_ body: () throws -> Void) -> Error? {
        do {
            try body()
            return nil
        } catch {
            return error
        }
    }

    // MARK: - Key generation

    private func generateECDSAKey(bits: Int, passphrase: String = "") throws -> String {
        try generateKey(type: "ecdsa", bits: bits, passphrase: passphrase)
    }

    private func generateEd25519Key(passphrase: String = "") throws -> String {
        try generateKey(type: "ed25519", bits: nil, passphrase: passphrase)
    }

    private func generateKey(type: String, bits: Int?, passphrase: String) throws -> String {
        let path = workDirectory.appendingPathComponent("id-\(type)-\(UUID().uuidString)")
        var arguments = ["-q", "-t", type, "-N", passphrase, "-C", "citadel-test", "-f", path.path]
        if let bits {
            arguments.append(contentsOf: ["-b", "\(bits)"])
        }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/ssh-keygen")
        process.arguments = arguments
        process.standardInput = FileHandle.nullDevice
        let output = Pipe()
        process.standardOutput = output
        process.standardError = output
        try process.run()
        let log = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            throw KeyGenerationFailure(
                arguments: arguments,
                status: process.terminationStatus,
                output: String(decoding: log, as: UTF8.self)
            )
        }

        return try String(contentsOf: path, encoding: .utf8)
    }

    private struct KeyGenerationFailure: Error, CustomStringConvertible {
        let arguments: [String]
        let status: Int32
        let output: String

        var description: String {
            "ssh-keygen \(arguments.joined(separator: " ")) exited \(status): \(output)"
        }
    }
}

/// The unencrypted head of an `openssh-key-v1` container, read without Citadel.
///
/// Layout, after the `openssh-key-v1\0` magic: `string cipher`,
/// `string kdfname`, `string kdfoptions`, `uint32 numberOfKeys`, then
/// `string publicKey` — which for ECDSA holds `string keytype`, `string curve`,
/// `string Q`. That head is in the clear even in a passphrase-protected file,
/// which is why these tests can compare against it either way.
private struct OpenSSHContainerHeader {
    let keyType: String
    let curve: String
    let point: Data

    init(pemEncoded key: String) throws {
        let body = key
            .split(separator: "\n")
            .filter { !$0.hasPrefix("-----") }
            .joined()
        guard let data = Data(base64Encoded: body) else {
            throw ReadFailure.notBase64
        }

        var reader = BlobReader(data)
        guard try reader.read(15) == Array("openssh-key-v1\0".utf8) else {
            throw ReadFailure.notAnOpenSSHContainer
        }
        _ = try reader.readString() // cipher
        _ = try reader.readString() // kdf name
        _ = try reader.readString() // kdf options
        _ = try reader.readUInt32() // number of keys

        var publicKey = BlobReader(Data(try reader.readString()))
        keyType = String(decoding: try publicKey.readString(), as: UTF8.self)
        curve = String(decoding: try publicKey.readString(), as: UTF8.self)
        point = Data(try publicKey.readString())
    }

    enum ReadFailure: Error {
        case notBase64, notAnOpenSSHContainer, truncated
    }

    private struct BlobReader {
        private let bytes: [UInt8]
        private var index = 0

        init(_ data: Data) {
            bytes = Array(data)
        }

        mutating func read(_ count: Int) throws -> [UInt8] {
            guard count >= 0, index + count <= bytes.count else {
                throw ReadFailure.truncated
            }
            defer { index += count }
            return Array(bytes[index..<(index + count)])
        }

        mutating func readUInt32() throws -> UInt32 {
            let raw = try read(4)
            return raw.reduce(UInt32(0)) { ($0 << 8) | UInt32($1) }
        }

        mutating func readString() throws -> [UInt8] {
            try read(Int(try readUInt32()))
        }
    }
}

/// Writes the `openssh-key-v1` container the parser reads, for a key whose
/// scalar the test picked on purpose.
///
/// Only the unencrypted form: `cipher` and `kdf` are `none`, so the private
/// section is in the clear and padded to the 8-byte block that form uses.
private enum OpenSSHContainerWriter {
    static func p256Container(for key: P256.Signing.PrivateKey) -> String {
        let keyType = "ecdsa-sha2-nistp256"
        let curve = "nistp256"
        let point = Array(key.publicKey.x963Representation)

        var publicSection = BlobWriter()
        publicSection.writeString(keyType)
        publicSection.writeString(curve)
        publicSection.writeBytes(point)

        var privateSection = BlobWriter()
        let check = UInt32.random(in: .min ... .max)
        privateSection.writeUInt32(check)
        privateSection.writeUInt32(check)
        privateSection.writeString(keyType)
        privateSection.writeString(curve)
        privateSection.writeBytes(point)
        privateSection.writeBytes(mpint(Array(key.rawRepresentation)))
        privateSection.writeString("citadel-test")
        privateSection.pad(toBlockSize: 8)

        var container = BlobWriter()
        container.writeRaw(Array("openssh-key-v1\0".utf8))
        container.writeString("none")
        container.writeString("none")
        container.writeBytes([])
        container.writeUInt32(1)
        container.writeBytes(publicSection.bytes)
        container.writeBytes(privateSection.bytes)

        let base64 = Data(container.bytes).base64EncodedString()
        return """
        -----BEGIN OPENSSH PRIVATE KEY-----
        \(base64)
        -----END OPENSSH PRIVATE KEY-----
        """
    }

    /// The SSH mpint encoding of a fixed-width scalar: no redundant leading
    /// zeroes, and a 0x00 sign byte whenever the top bit is set.
    private static func mpint(_ scalar: [UInt8]) -> [UInt8] {
        var bytes = Array(scalar.drop { $0 == 0x00 })

        if let first = bytes.first, first & 0x80 != 0 {
            bytes.insert(0x00, at: 0)
        }

        return bytes
    }

    private struct BlobWriter {
        private(set) var bytes: [UInt8] = []

        mutating func writeRaw(_ raw: [UInt8]) {
            bytes.append(contentsOf: raw)
        }

        mutating func writeUInt32(_ value: UInt32) {
            bytes.append(contentsOf: [
                UInt8(truncatingIfNeeded: value >> 24),
                UInt8(truncatingIfNeeded: value >> 16),
                UInt8(truncatingIfNeeded: value >> 8),
                UInt8(truncatingIfNeeded: value),
            ])
        }

        mutating func writeBytes(_ payload: [UInt8]) {
            writeUInt32(UInt32(payload.count))
            writeRaw(payload)
        }

        mutating func writeString(_ string: String) {
            writeBytes(Array(string.utf8))
        }

        mutating func pad(toBlockSize blockSize: Int) {
            let remainder = bytes.count % blockSize

            if remainder != 0 {
                writeRaw((1...(blockSize - remainder)).map(UInt8.init))
            }
        }
    }
}
